name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: Private registry
  ECR_REPOSITORY: front_endimage
  ECS_SERVICE: front_endimage
  ECS_CLUSTER: front_endimage
  ECS_TASK_DEFINITION: front_endtask.json
  CONTAINER_NAME: myimage

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Build Docker image
      run: |
        docker build -t $ECR_REPOSITORY:${{ github.sha }} -f Dockerfile .
        docker tag $ECR_REPOSITORY:${{ github.sha }} $ECR_REPOSITORY:latest
        

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Push image to Amazon ECR
      run: |
       
        echo "Pushing the Docker images..."
        docker push $ECR_REGISTRY/${ECR_REPOSITORY}:latest
       
    - name: Update ECS service
      run: |
        aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment
